name: binder
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy>=1.16.3,<2
  - scikit-image
  - nibabel>=5.3.2,<6
  - jupyterlab
  - notebook
  - ipywidgets
  - pip
  - pip:
    - ipyniivue>=2.4.2
